## Configuracion de Spring
spring:
  application:
    name: ms-usuarios
  datasource:
    url: jdbc:postgresql://149.56.110.32:8585/ms-usuarios
    username: avalon
    password: avalon_psw
    hikari:
      max-lifetime: 1800000  # 30 minutes in milliseconds

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#      ddl-auto: create

  mail:
    host: smtp.gmail.com
    port: 587
    username: bryamgmfn@gmail.com
    password: magaly00
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
          ssl:
            trust: "*"

server:
  port: 8086

## Configuracion del cliente de Eureka
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: ms-usuarios

jwt:
  secret: HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512HmacSHA512
  expiration: 31536000000  # Representaría 1,000 años en milisegundos
